name: '${project.artifactId}'
version: '${project.version}'
api-version: "1.21"
main: at.flauschigesalex.resource_pack_loader.minecraft.paper.ResourceLoaderPaper
authors:
  - "FlauschigesAlex"
website: "https://modrinth.com/plugin/resource-pack-loader"